name: Generate ASCII Artwork
on: 
  push
jobs: 
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4  
        - name: Install Cowsay
          run : sudo apt-get install cowsay -y  
        - name: Execute Cowsay CMD
          run : cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
        - name: Upload The Dragon File
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: dragon.txt
          

    test_job_1:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: Download The Dragon File
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file
        - name: Test File Exists
          run : grep -i "dragon" dragon.txt
    
    deploy_job_1:
        needs: test_job_1
        runs-on: ubuntu-latest
        steps:
        - name: Download The Dragon File
          uses: actions/download-artifact@v4
          with:
            name: dragon-text-file
        - name: Read the File
          run : cat dragon.txt

